# Generated by Django 2.2.3 on 2019-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
