# Generated by Django 2.2.3 on 2019-08-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20190731_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
