# Generated by Django 2.2.3 on 2019-08-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_bid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write',
            name='biddings',
        ),
        migrations.AddField(
            model_name='write',
            name='biddings',
            field=models.CharField(default="{'li':[]}", max_length=200),
        ),
    ]
