# Generated by Django 2.2.3 on 2019-08-07 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0006_auto_20190807_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='category',
            field=models.CharField(blank=True, choices=[('식품', '식품'), ('가구/생활/건강', '가구/생활/건강'), ('디지털/가전', '디지털/가전'), ('의류/잡화', '의류/잡화'), ('뷰티', '뷰티'), ('도서/취미/상품권', '도서/취미/상품권'), ('레저/자동차', '레저/자동차'), ('반려동물', '반려동물')], max_length=10),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1, null=True)),
                ('comment', models.CharField(max_length=30, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
