# Generated by Django 2.2.3 on 2019-08-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(null=True)),
                ('url', models.TextField()),
                ('recruit', models.PositiveIntegerField(default=0)),
                ('lookup', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPurchase',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('lookup', models.IntegerField(default=0)),
            ],
        ),
    ]
