# Generated by Django 2.2.3 on 2019-08-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouppurchase', '0002_remove_grouppurchase_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppurchase',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
